apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: core-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.19.7
  name: core-dns-coredns
  namespace: host-dns
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 5s
        }
        log
        etcd {
            endpoint http://etcd-dns.host-dns:2379
        }
        cache 30
        prometheus 0.0.0.0:9153
        reload
        loadbalance
    }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: core-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.19.7
  name: core-dns-coredns
  namespace: host-dns
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
      - pods
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: core-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.19.7
  name: core-dns-coredns
  namespace: host-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: core-dns-coredns
subjects:
  - kind: ServiceAccount
    name: default
    namespace: host-dns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: core-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.19.7
  name: core-dns-coredns
  namespace: host-dns
spec:
  ports:
    - name: udp-53
      port: 53
      protocol: UDP
    - name: tcp-53
      port: 53
      protocol: TCP
  selector:
    app.kubernetes.io/instance: core-dns
    app.kubernetes.io/name: coredns
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: core-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    app.kubernetes.io/version: 1.9.4
    helm.sh/chart: coredns-1.19.7
  name: core-dns-coredns
  namespace: host-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: core-dns
      app.kubernetes.io/name: coredns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: ef161d21e876601d493e3ffbcf13b947c5142a717fbc5812f6b636ade1b6b034
      labels:
        app.kubernetes.io/instance: core-dns
        app.kubernetes.io/name: coredns
    spec:
      containers:
        - args:
            - -conf
            - /etc/coredns/Corefile
          image: coredns/coredns:1.9.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: coredns
          ports:
            - containerPort: 53
              name: udp-53
              protocol: UDP
            - containerPort: 53
              name: tcp-53
              protocol: TCP
            - containerPort: 9153
              name: tcp-9153
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/coredns
              name: config-volume
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            items:
              - key: Corefile
                path: Corefile
            name: core-dns-coredns
          name: config-volume
